// uploading/vue-upload/src/views/Home.vue
<template>
  <main>
     <h2>VueJS File Upload</h2>
    <form @submit="sendFile($event)" id="upload_form" enctype="multipart/form-data" method="post">
        <input ref="inputFile" type="file" name="file1" id="file1"><br>
        <progress ref="progressBar" id="progressBar" value="0" max="100" style="width:300px;"></progress>
        <h3 id="status">{{ status }}</h3>
        <p id="loaded_n_total">{{ progressText }}</p>
        <hr />
        <button type="submit">Enviar arquivo</button>
    </form>

  </main>
</template>

<script>
// @ is an alias to /src
// import HelloWorld from '@/components/HelloWorld.vue'

export default {
  name: 'Home',

  methods: {
    sendFile(e) {
      e.preventDefault();
      let file = this.$refs.inputFile?.files[0];
      if(file) {
        let fd = new FormData();
        fd.append("file", file, "video.mov");
        this.$http.post('http://localhost:5000/profile/upload', fd, {
          onUploadProgress: event => {
            let percent = Math.round((event.loaded / event.total) * 100);
            this.$refs.progressBar.value = percent;
            this.$data.progressText = percent + "% uploaded... please wait";
          }
        })
          .then(result => {
            this.$data.status = result.data;
            this.$data.progressText = 'Uploaded';
          });
      }
    }
  },

  data() {
    return {
      status: '',
      progressText: '',
    };
  },

 


}
</script>

// uploading/angular-upload/src/app/home/home.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { HttpClient, HttpEventType } from '@angular/common/http';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  @ViewChild('inputFile')
  inputFile: ElementRef;

  @ViewChild('progressBar')
  progressBar: ElementRef;

  uploadStatus: string = '';

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit(): void {
  }

  sendFile() {
    let file: File = this.inputFile.nativeElement.files[0];
    let formData = new FormData();
    formData.append("file", file, "video.mov");

    this.http.post('http://localhost:5000/profile/upload', formData, {
      observe: 'events',
      reportProgress: true
    }).subscribe(event => {
      switch (event.type) {
        case HttpEventType.UploadProgress:
          console.log('Uploading....');
          let p = (event.loaded / event.total) * 100;
          (<HTMLProgressElement> this.progressBar.nativeElement).value = Math.round(p);
          this.uploadStatus = "Uploaded " + event.loaded + " bytes of " + event.total;
      break;
        case HttpEventType.Response:
          console.log('Response', event.status, event.body);
      break;
        default:
          return `File "x" surprising upload event: ${event.type}.`;
      }
    })
  }
}

<h2>Vanilla File Upload</h2>
<form (submit)="sendFile()" id="upload_form" enctype="multipart/form-data" method="post">
    <input #inputFile type="file" name="file1" id="file1"><br>
    <progress #progressBar id="progressBar" value="0" max="100" style="width:300px;"></progress>
    <h3 id="status"></h3>
    <p id="loaded_n_total">{{ uploadStatus }}</p>
    <hr />
    <button type="submit">Enviar arquivo</button>
</form>
